const SECTIONS = [
  {
    id: "section1",
    gridId: "grid1",
    level: "beginner",
    cornerColor: "var(--green)",
  },
  {
    id: "section2",
    gridId: "grid2",
    level: "medium",
    cornerColor: "var(--yellow)",
  },
  {
    id: "section3",
    gridId: "grid3",
    level: "expert",
    cornerColor: "var(--pink)",
  },
  // Добавляем новые секции ниже по такому же шаблону
  // {
  //   id: "section4",
  //   gridId: "grid4",
  //   level: "master",
  //   cornerColor: "var(--accent)",
  // },
];

const GAMES = [
  // НОВИЧОК
  {
    sectionId: "section1",
    id: "sorter",
    emoji: "𝄃𝄃𝄂𝄂𝄀𝄁𝄃𝄂𝄂𝄃",
    title: "Сортировщик",
    desc: "Сортируй блоки кода по правильным корзинам до того, как они упадут",
    tags: ["beginner"],
    stars: 1,
    wip: false,
    link: "games/sorter/index.html",
  },
  {
    sectionId: "section1",
    id: "network",
    emoji: "🌐",
    title: "Сетевой маршрут",
    desc: "Определи, какое устройство может получить пакет данных по IP-адресу и маске подсети",
    tags: ["beginner"],
    stars: 2,
    wip: false,
    link: "games/network/index.html",
  },
  {
    sectionId: "section1",
    id: "newgame2",
    emoji: "𝄃𝄃𝄂𝄂𝄀𝄁𝄃𝄂𝄂𝄃",
    title: "ИГРА 2",
    desc: "Скоро здесь что-то появится",
    tags: ["beginner"],
    stars: 2,
    wip: true,
    link: "#",
  },
  {
    sectionId: "section1",
    id: "newgame3",
    emoji: "𝄃𝄃𝄂𝄂𝄀𝄁𝄃𝄂𝄂𝄃",
    title: "ИГРА 3",
    desc: "Скоро здесь что-то появится",
    tags: ["beginner"],
    stars: 3,
    wip: true,
    link: "#",
  },
  {
    sectionId: "section1",
    id: "newgame4",
    emoji: "𝄃𝄃𝄂𝄂𝄀𝄁𝄃𝄂𝄂𝄃",
    title: "ИГРА 4",
    desc: "Скоро здесь что-то появится",
    tags: ["beginner"],
    stars: 4,
    wip: true,
    link: "#",
  },

  // ——— ПРАКТИК ———
  {
    sectionId: "section2",
    id: "millionaire",
    emoji: "💻",
    title: "Кто хочет стать программистом?",
    desc: "15 вопросов по Python и C++. 4 подсказки. Доберись до миллиона!",
    tags: ["medium"],
    stars: 3,
    wip: false,
    link: "games/millionaire/index.html",
  },
  {
    sectionId: "section2",
    id: "pixelgame",
    emoji: "👾",
    title: "CodeQuest — Внутри компьютера",
    desc: "Пиксельная RPG: исследуй лабиринт, открывай сундуки с кодом и собери программу на Go",
    tags: ["medium"],
    stars: 2,
    wip: false, // карточка кликабельна; статус WIP для карусели управляется в admin/games.php (БД)
    link: "games/pixelgame/index.html",
  },
  {
    sectionId: "section2",
    id: "newgame6",
    emoji: "𝄃𝄃𝄂𝄂𝄀𝄁𝄃𝄂𝄂𝄃",
    title: "ИГРА 6",
    desc: "Скоро здесь что-то появится",
    tags: ["medium"],
    stars: 3,
    wip: true,
    link: "#",
  },
  {
    sectionId: "section2",
    id: "newgame7",
    emoji: "𝄃𝄃𝄂𝄂𝄀𝄁𝄃𝄂𝄂𝄃",
    title: "ИГРА 7",
    desc: "Скоро здесь что-то появится",
    tags: ["medium"],
    stars: 2,
    wip: true,
    link: "#",
  },
  {
    sectionId: "section2",
    id: "newgame8",
    emoji: "𝄃𝄃𝄂𝄂𝄀𝄁𝄃𝄂𝄂𝄃",
    title: "ИГРА 8",
    desc: "Скоро здесь что-то появится",
    tags: ["medium"],
    stars: 3,
    wip: true,
    link: "#",
  },

  // ——— ЭКСПЕРТ ———
  {
    sectionId: "section3",
    id: "newgame9",
    emoji: "𝄃𝄃𝄂𝄂𝄀𝄁𝄃𝄂𝄂𝄃",
    title: "ИГРА 9",
    desc: "Скоро здесь что-то появится",
    tags: ["expert"],
    stars: 3,
    wip: true,
    link: "#",
  },
  {
    sectionId: "section3",
    id: "newgame10",
    emoji: "𝄃𝄃𝄂𝄂𝄀𝄁𝄃𝄂𝄂𝄃",
    title: "ИГРА 10",
    desc: "Скоро здесь что-то появится",
    tags: ["expert"],
    stars: 3,
    wip: true,
    link: "#",
  },
  {
    sectionId: "section3",
    id: "newgame11",
    emoji: "𝄃𝄃𝄂𝄂𝄀𝄁𝄃𝄂𝄂𝄃",
    title: "ИГРА 11",
    desc: "Скоро здесь что-то появится",
    tags: ["expert"],
    stars: 2,
    wip: true,
    link: "#",
  },
  {
    sectionId: "section3",
    id: "newgame12",
    emoji: "𝄃𝄃𝄂𝄂𝄀𝄁𝄃𝄂𝄂𝄃",
    title: "ИГРА 12",
    desc: "Скоро здесь что-то появится",
    tags: ["expert"],
    stars: 3,
    wip: true,
    link: "#",
  },
];
